#!/bin/sh

echo "Running tests before commit..."

cd Assignment_4

pytest test.py

if [ $? -ne 0 ]; then
    echo "Tests failed. Commit aborted."
    exit 1
fi

echo "All tests passed. Proceeding with commit."
exit 0